### DISCUSSION TITLE
Package releases via github actions

### DISCUSSION THREAD

**Discussion by marksweb** [django-cms/django-cms#7157] [General]
Releasing packages is, I think it's fair to say, a bottleneck currently for us.

There has however, been some talk on Slack of automating the release process. This can be done with github actions, with the only decision required being, what do we want to be the trigger for a release.

An example action for pypi releases;

```
name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
``` 

In this example which I've put together for [django-bleach](https://github.com/marksweb/django-bleach), on each push the application is built and uploaded to `test.pypi.org/legacy/` to ensure that the changes could potentially be released. Then if a commit is tagged, it'd trigger a release to `pypi.org`.

I don't think we'd necessarily want to use the tag trigger, but there are different options the most appropriate might be the creation of a release, in which case we'd probably have two actions, with the test.pypi.org release being on push/PR and the official release being triggered after someone creates the release (which can also create the tag once a branch is ready.

```
name: Publish Python 🐍 distributions 📦 to PyPI

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
```

If we can agree on how we'd like releases triggered, we then just need to get token's generated in pypi and added to each repo's secrets, then we can get these actions added.
