### ISSUE TITLE
Previous fix for Django Debug Toolbar prevents proper operation in newer releases

### ISSUE THREAD

**Issue by mkoistinen** [django-cms/django-cms#2476]
Probably as a fix for #1757, CSS was added to place the Django Debug Toolbar into a specific place.

It seems that in newer versions of DDT allow the UI tab to be moved into whatever place makes sense for the user.  The fix in django-cms code base prevents that from working.

Solution:
Delete the line: https://github.com/divio/django-cms/blob/develop/cms/static/cms/sass/cms.base.scss#L53

Which reads:

``` scss
#djDebug #djDebugToolbarHandle { top:35px !important; border-right:none !important; }
```

And instead users should upgrade DDT to a newer release.

There is still the issue that DDT wants to also appear in the sideframe.  Which is annoying and possibly worse, but it is useable with the above change.
